"use client";

import { useEffect, useState } from "react";
import styles from "./demo.module.css";

type Role = "hq" | "manager" | "staff";
type View = "dashboard" | "stores" | "inventory" | "orders" | "people" | "attendance" | "guide";
type OrderStatus = "요청" | "승인" | "준비 중" | "출고" | "입고 완료";
type Store = { id:string; name:string; region:string; address:string; manager:string; lat:number; lng:number; active:boolean };
type User = { id:number; name:string; loginId:string; role:Role; storeIds:string[]; active:boolean };
type Order = { id:number; store:string; item:string; qty:number; needed:string; note:string; status:OrderStatus; by:string };
type Attend = { id:number; userId:number; storeId:string; date:string; start:string; end?:string; distance:number; accuracy:number; status:"근무 중"|"퇴근" };
type State = { stores:Store[]; users:User[]; stock:Record<string,Record<string,number>>; orders:Order[]; attendance:Attend[] };

const items = [
  {id:"rice",name:"쌀겨",unit:"포",safe:5,target:12},{id:"culture",name:"배양액",unit:"통",safe:4,target:10},
  {id:"enzyme",name:"효소 분말",unit:"박스",safe:3,target:8},{id:"robe",name:"찜질복",unit:"벌",safe:12,target:30},
  {id:"towel",name:"대형 타월",unit:"장",safe:20,target:50},{id:"tea",name:"웰컴티",unit:"박스",safe:3,target:8},
  {id:"cleaner",name:"천연 세정제",unit:"통",safe:4,target:10},
];
const baseStores:Store[] = [
  ["gildong","길동점","서울 강동구","서울 강동구 양재대로 1481","김지연",37.5385,127.1427],
  ["ilsan","일산점","경기 고양시","경기 고양시 일산서구 중앙로 1432","박소연",37.6758,126.7477],
  ["guri","구리점","경기 구리시","경기 구리시 경춘로 242","이민정",37.6034,127.1432],
  ["bundang","분당점","경기 성남시","경기 성남시 분당구 성남대로 601","최은서",37.3827,127.1190],
  ["songdo","송도점","인천 연수구","인천 연수구 센트럴로 123","한유진",37.3850,126.6413],
  ["suwon","수원점","경기 수원시","경기 수원시 팔달구 효원로 241","정다은",37.2636,127.0286],
  ["cheonan","천안점","충남 천안시","충남 천안시 서북구 번영로 156","오수빈",36.8151,127.1139],
  ["daejeon","대전점","대전 서구","대전 서구 둔산로 100","윤서현",36.3504,127.3845],
  ["daegu","대구점","대구 중구","대구 중구 국채보상로 670","이지수",35.8714,128.6014],
  ["busan","부산점","부산 부산진구","부산 부산진구 중앙대로 730","강하늘",35.1579,129.0596],
  ["gwangju","광주점","광주 서구","광주 서구 내방로 111","문채원",35.1595,126.8526],
  ["jeju","제주점","제주 제주시","제주 제주시 문연로 6","임가은",33.4890,126.4983],
].map(x=>({id:x[0] as string,name:x[1] as string,region:x[2] as string,address:x[3] as string,manager:x[4] as string,lat:x[5] as number,lng:x[6] as number,active:true}));
const makeStock=(n:number)=>Object.fromEntries(items.map((i,k)=>[i.id,((n+2)*(k+3)*7)%58]));
const initial=():State=>({stores:baseStores,users:[{id:1,name:"본사 관리자",loginId:"hq.admin",role:"hq",storeIds:[],active:true},...baseStores.map((s,n)=>({id:n+10,name:s.manager,loginId:`${s.id}.owner`,role:"manager" as Role,storeIds:[s.id],active:true})),{id:40,name:"김하린",loginId:"gildong.staff",role:"staff",storeIds:["gildong"],active:true}],stock:Object.fromEntries(baseStores.map((s,n)=>[s.id,makeStock(n)])),orders:[{id:1042,store:"gildong",item:"rice",qty:10,needed:"2026-09-13",note:"주말 예약 증가 대비",status:"요청",by:"김지연"},{id:1041,store:"ilsan",item:"culture",qty:6,needed:"2026-09-12",note:"현재 재고 3통",status:"승인",by:"박소연"},{id:1040,store:"guri",item:"cleaner",qty:8,needed:"2026-09-11",note:"정기 보충",status:"출고",by:"이민정"}],attendance:[]});
const key="hyososup-demo-v2";
const clone=()=>JSON.parse(JSON.stringify(initial())) as State;
const rad=(n:number)=>n*Math.PI/180;
function meters(a:{lat:number;lng:number},b:{lat:number;lng:number}){const dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng);const q=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLng/2)**2;return 12742000*Math.asin(Math.sqrt(q))}

export default function Demo(){
  const [data,setData]=useState<State>(clone);
  const [role,setRole]=useState<Role>("hq"); const [storeId,setStoreId]=useState("gildong"); const [view,setView]=useState<View>("dashboard");
  const [guide,setGuide]=useState(true); const [notice,setNotice]=useState("전국 점포 현황을 지도와 목록으로 확인할 수 있습니다.");
  const [query,setQuery]=useState(""); const [filter,setFilter]=useState("all"); const [modal,setModal]=useState<"store"|"person"|"order"|null>(null);
  const [gpsBusy,setGpsBusy]=useState(false); const [ready,setReady]=useState(false);
  const [storeDraft,setStoreDraft]=useState({name:"",region:"",address:"",manager:"",lat:"37.5385",lng:"127.1427"});
  const [personDraft,setPersonDraft]=useState({name:"",loginId:"",role:"manager" as Role,storeId:"gildong"});
  const [orderDraft,setOrderDraft]=useState({item:"rice",qty:5,needed:"2026-09-15",note:""});
  useEffect(()=>{document.title="효소숲 Store Hub 체험판";try{const saved=localStorage.getItem(key);if(saved)setData(JSON.parse(saved) as State)}catch{}setReady(true)},[]);
  useEffect(()=>{if(ready)localStorage.setItem(key,JSON.stringify(data))},[data,ready]);
  const store=data.stores.find(s=>s.id===storeId)??data.stores[0];
  const user=data.users.find(u=>u.role===role&&(role==="hq"||u.storeIds.includes(storeId)))??data.users[0];
  const accessible=role==="hq"?data.stores:data.stores.filter(s=>user.storeIds.includes(s.id));
  const lowCount=(s:Store)=>items.filter(i=>(data.stock[s.id]?.[i.id]??0)<=i.safe).length;
  const pendingCount=(id:string)=>data.orders.filter(o=>o.store===id&&!(["입고 완료"] as OrderStatus[]).includes(o.status)).length;
  const shown=accessible.filter(s=>`${s.name} ${s.region} ${s.manager}`.includes(query)&&((filter==="all")||(filter==="alert"?(lowCount(s)+pendingCount(s.id)>0):(lowCount(s)+pendingCount(s.id)===0)))).sort((a,b)=>lowCount(b)+pendingCount(b.id)-lowCount(a)-pendingCount(a.id));
  const total=accessible.reduce((a,s)=>a+items.reduce((b,i)=>b+(data.stock[s.id]?.[i.id]??0),0),0);
  const low=accessible.reduce((a,s)=>a+lowCount(s),0); const pending=accessible.reduce((a,s)=>a+pendingCount(s.id),0);
  const today=new Date().toLocaleDateString("sv-SE");

  function changeRole(r:Role){setRole(r);const next=data.users.find(u=>u.role===r);if(next?.storeIds[0])setStoreId(next.storeIds[0]);setView("dashboard");setNotice(r==="hq"?"본사 관리자: 모든 점포와 계정을 관리합니다.":r==="manager"?"점주: 자기 점포와 직원을 관리합니다.":"직원: 배정된 점포 업무만 이용합니다.")}
  function reset(){if(confirm("모든 체험 데이터를 초기화할까요?")){setData(clone());setRole("hq");setStoreId("gildong");setView("dashboard")}}
  function addStore(e:React.FormEvent){e.preventDefault();const id=`store-${Date.now()}`;const s:Store={id,name:storeDraft.name.trim(),region:storeDraft.region.trim(),address:storeDraft.address.trim(),manager:storeDraft.manager.trim()||"미배정",lat:Number(storeDraft.lat),lng:Number(storeDraft.lng),active:true};if(!s.name||!s.region||!s.address||!Number.isFinite(s.lat)||!Number.isFinite(s.lng))return;setData(d=>({...d,stores:[...d.stores,s],stock:{...d.stock,[id]:makeStock(d.stores.length)}}));setStoreId(id);setModal(null);setNotice(`${s.name}과 주소를 등록했습니다.`)}
  function addPerson(e:React.FormEvent){e.preventDefault();if(!personDraft.name.trim()||!personDraft.loginId.trim())return;const newRole=role==="hq"?personDraft.role:"staff";const assigned=role==="hq"?personDraft.storeId:storeId;setData(d=>({...d,users:[...d.users,{id:Date.now(),name:personDraft.name.trim(),loginId:personDraft.loginId.trim(),role:newRole,storeIds:newRole==="hq"?[]:[assigned],active:true}]}));setModal(null);setNotice(`${personDraft.name} 계정을 생성했습니다. 최초 로그인 때 비밀번호를 변경합니다.`)}
  function addOrder(e:React.FormEvent){e.preventDefault();if(orderDraft.qty<1||!orderDraft.needed)return;const o:Order={id:Math.max(...data.orders.map(o=>o.id))+1,store:storeId,item:orderDraft.item,qty:Math.floor(orderDraft.qty),needed:orderDraft.needed,note:orderDraft.note||"재고 보충 요청",status:"요청",by:user.name};setData(d=>({...d,orders:[o,...d.orders]}));setModal(null);setView("orders")}
  function orderStep(o:Order,next:OrderStatus){setData(d=>{let stock=d.stock;if(next==="입고 완료")stock={...stock,[o.store]:{...stock[o.store],[o.item]:(stock[o.store]?.[o.item]??0)+o.qty}};return{...d,stock,orders:d.orders.map(x=>x.id===o.id?{...x,status:next}:x)}})}
  function recordClock(distance:number,accuracy:number){if(data.attendance.some(a=>a.userId===user.id&&a.date===today)){setNotice("오늘 출근 기록이 이미 있습니다.");return}setData(d=>({...d,attendance:[{id:Date.now(),userId:user.id,storeId,date:today,start:new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"}),distance,accuracy,status:"근무 중"},...d.attendance]}));setNotice(`${store.name}에서 ${distance}m 거리로 출근 처리됐습니다.`)}
  function clockIn(){if(role==="hq")return;if(!navigator.geolocation){setNotice("GPS를 지원하지 않는 기기입니다.");return}setGpsBusy(true);navigator.geolocation.getCurrentPosition(p=>{const d=Math.round(meters({lat:p.coords.latitude,lng:p.coords.longitude},store)),a=Math.round(p.coords.accuracy);if(a>100)setNotice(`GPS 오차가 ±${a}m로 커서 다시 측정해야 합니다.`);else if(d>50)setNotice(`점포에서 ${d.toLocaleString()}m 떨어져 출근이 인정되지 않았습니다.`);else recordClock(d,a);setGpsBusy(false)},()=>{setNotice("위치 권한이 없어 출근을 처리하지 못했습니다.");setGpsBusy(false)},{enableHighAccuracy:true,timeout:12000,maximumAge:0})}
  function clockOut(id:number){setData(d=>({...d,attendance:d.attendance.map(a=>a.id===id?{...a,end:new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"}),status:"퇴근"}:a)}))}
  const nav:[View,string,string][]=[["dashboard","▦","통합 현황"],["stores","⌖","점포 지도"],["inventory","◫","점포 재고"],["orders","⇄","수발주"],["people","♙","계정 관리"],["attendance","◷","출퇴근"],["guide","?","도입 안내"]];

  return <main className={styles.app}>
    <header className={styles.header}><div className={styles.brand}><b>酵</b><span><strong>효소숲 Store Hub</strong><small>전국 가맹점 운영을 한곳에서</small></span></div><div className={styles.headerButtons}><i>EXPANDED DEMO</i><button onClick={()=>setGuide(true)}>체험 가이드</button><button onClick={reset}>초기화</button></div></header>
    <section className={styles.rolebar}><div><small>현재 역할</small><span className={styles.roles}>{(["hq","manager","staff"] as Role[]).map(r=><button key={r} className={role===r?styles.selected:""} onClick={()=>changeRole(r)}>{r==="hq"?"본사 관리자":r==="manager"?"점주·지점장":"점포 직원"}</button>)}</span></div>{role!=="hq"&&<label>담당 점포<select value={storeId} onChange={e=>setStoreId(e.target.value)}>{accessible.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<p>{user.name} · {role==="hq"?"전국 관리":store.name}</p></section>
    {notice&&<aside className={styles.toast}>●　{notice}<button onClick={()=>setNotice("")}>×</button></aside>}
    <div className={styles.layout}><nav className={`${styles.nav} ${styles.scaleNav}`}>{nav.filter(([v])=>role==="hq"||v!=="stores").map(([v,icon,label])=><button key={v} className={view===v?styles.navOn:""} onClick={()=>setView(v)}><b>{icon}</b>{label}{v==="orders"&&<i>{pending}</i>}</button>)}</nav><section className={styles.content}>
      {view==="dashboard"&&<><Title eyebrow="NATIONAL OVERVIEW" title={role==="hq"?"전국 점포 운영 현황":`${store.name} 운영 현황`} body="정상 점포보다 지금 조치가 필요한 점포를 먼저 보여드립니다." action={role==="hq"?()=>setModal("store"):()=>setModal("order")} label={role==="hq"?"+ 점포 생성":"+ 물품 요청"}/><div className={styles.metrics}><Metric label="운영 점포" value={accessible.length} sub="개 점포"/><Metric label="전체 재고" value={total} sub="전 품목 합계"/><Metric label="부족 품목" value={low} sub="즉시 확인 필요" warn/><Metric label="진행 중 발주" value={pending} sub="요청부터 입고까지"/></div><div className={styles.columns}><Panel title="조치 필요 점포" sub="부족 재고와 미처리 발주가 많은 순서"><StoreList stores={shown.slice(0,7)} low={lowCount} pending={pendingCount} pick={id=>{setStoreId(id);setView("inventory")}}/></Panel><Panel title="전국 점포 분포" sub="초록 정상 · 노랑 주의 · 빨강 긴급"><Map stores={accessible} low={lowCount} pick={id=>{setStoreId(id);setView("inventory")}}/></Panel></div></>}
      {view==="stores"&&<><Title eyebrow="STORE NETWORK" title="전국 점포 지도" body="지도에서 분포를 보고, 목록에서 검색·정렬해 업무를 처리합니다." action={()=>setModal("store")} label="+ 점포 생성"/><div className={styles.columns}><Panel title="점포 위치" sub="시·군·구당 한 점포를 선명하게 표시"><Map stores={data.stores} low={lowCount} pick={setStoreId}/></Panel><Panel title="점포 검색" sub={`${shown.length}개 점포 표시`}><Filters query={query} setQuery={setQuery} filter={filter} setFilter={setFilter}/><StoreList stores={shown} low={lowCount} pending={pendingCount} pick={id=>{setStoreId(id);setView("inventory")}}/></Panel></div></>}
      {view==="inventory"&&<><Title eyebrow="STORE INVENTORY" title={`${store.name} 재고`} body={`${store.region} · 점주 ${store.manager} · ${store.address}`} action={role!=="staff"?()=>setModal("order"):undefined} label="+ 물품 요청"/>{role==="hq"&&<div className={styles.filters}><input placeholder="점포명 검색" value={query} onChange={e=>setQuery(e.target.value)}/><select value={storeId} onChange={e=>setStoreId(e.target.value)}>{data.stores.filter(s=>`${s.name} ${s.region}`.includes(query)).map(s=><option key={s.id} value={s.id}>{s.name} · {s.region}</option>)}</select></div>}<Panel title="품목별 현재고" sub="안전재고 이하 품목은 자동으로 강조됩니다."><div className={styles.inventory}>{items.map(i=>{const q=data.stock[storeId]?.[i.id]??0,bad=q<=i.safe;return <article className={bad?styles.lowItem:""} key={i.id}><header><small>공통 품목</small><b>{bad?"보충 필요":"적정"}</b></header><h3>{i.name}</h3><strong>{q}<small>{i.unit}</small></strong><div><i style={{width:`${Math.min(100,q/i.target*100)}%`}}/></div><p>안전 {i.safe}{i.unit} · 권장 {i.target}{i.unit}</p></article>})}</div></Panel></>}
      {view==="orders"&&<><Title eyebrow="SMART REPLENISHMENT" title="수발주 관리" body="요청부터 본사 승인·출고·점포 입고까지 한 흐름으로 연결합니다." action={role!=="staff"?()=>setModal("order"):undefined} label="+ 물품 요청"/><Panel title="요청 진행 현황" sub="역할을 바꾸며 전체 처리 과정을 체험하세요."><div className={styles.orders}>{data.orders.filter(o=>role==="hq"||o.store===storeId).map(o=><article key={o.id}><div className={styles.orderMain}><Status value={o.status}/><span><small>#{o.id} · {data.stores.find(s=>s.id===o.store)?.name}</small><h3>{items.find(i=>i.id===o.item)?.name} <b>{o.qty}{items.find(i=>i.id===o.item)?.unit}</b></h3><p>{o.note} · 필요일 {o.needed} · {o.by}</p></span></div><div className={styles.actions}>{role==="hq"&&o.status==="요청"&&<button className={styles.primarySmall} onClick={()=>orderStep(o,"승인")}>승인</button>}{role==="hq"&&o.status==="승인"&&<button className={styles.primarySmall} onClick={()=>orderStep(o,"준비 중")}>준비 시작</button>}{role==="hq"&&o.status==="준비 중"&&<button className={styles.primarySmall} onClick={()=>orderStep(o,"출고")}>출고 완료</button>}{role!=="hq"&&o.status==="출고"&&<button className={styles.primarySmall} onClick={()=>orderStep(o,"입고 완료")}>수령·입고</button>}</div></article>)}</div></Panel></>}
      {view==="people"&&<><Title eyebrow="ROLE & ACCOUNT" title="계정 및 권한 관리" body={role==="hq"?"본사는 점주와 직원을, 점주는 자기 점포 직원만 관리합니다.":`${store.name} 직원만 생성하고 관리할 수 있습니다.`} action={role!=="staff"?()=>{setPersonDraft(p=>({...p,role:role==="hq"?"manager":"staff",storeId}));setModal("person")}:undefined} label="+ 계정 생성"/><Panel title="사용자 목록" sub="계정을 중지해도 과거 업무와 근태 기록은 유지됩니다."><div className={styles.people}>{data.users.filter(u=>role==="hq"||u.storeIds.includes(storeId)).map(u=><article key={u.id}><span><b>{u.name}</b><small>{u.loginId} · {u.role==="hq"?"본사":u.role==="manager"?"점주·지점장":"직원"}</small></span><em>{u.storeIds.map(id=>data.stores.find(s=>s.id===id)?.name).filter(Boolean).join(", ")||"전체"}</em><strong className={u.active?styles.good:styles.bad}>{u.active?"사용 중":"중지"}</strong>{role!=="staff"&&u.role!=="hq"&&<button onClick={()=>setData(d=>({...d,users:d.users.map(x=>x.id===u.id?{...x,active:!x.active}:x)}))}>{u.active?"중지":"복원"}</button>}</article>)}</div></Panel></>}
      {view==="attendance"&&<><Title eyebrow="GPS ATTENDANCE" title="출퇴근 관리" body="등록된 점포 주소의 GPS 좌표 반경 50m 이내 로그인만 출근으로 인정합니다."/><div className={styles.attendanceHero}><div><small>현재 근무지</small><h2>{store.name}</h2><p>{store.address}</p><b>허용 반경 50m</b></div><div><button className={styles.primary} onClick={clockIn} disabled={gpsBusy||role==="hq"}>{gpsBusy?"GPS 확인 중…":"GPS로 출근"}</button><button onClick={()=>role!=="hq"&&recordClock(18,12)} disabled={role==="hq"}>체험용 출근</button><small>{role==="hq"?"직원 역할로 전환해 체험하세요.":"위치 권한을 허용하면 실제 거리를 계산합니다."}</small></div></div><Panel title={role==="hq"?"전체 점포 근태 현황":`${store.name} 근태 현황`} sub="출근 거리와 GPS 정확도를 함께 기록합니다."><div className={styles.people}>{data.attendance.filter(a=>role==="hq"||a.storeId===storeId).map(a=><article key={a.id}><span><b>{data.users.find(u=>u.id===a.userId)?.name}</b><small>{a.date} · {a.start}{a.end?` ~ ${a.end}`:""}</small></span><em>{data.stores.find(s=>s.id===a.storeId)?.name} · {a.distance}m · 오차 ±{a.accuracy}m</em><strong>{a.status}</strong>{a.status==="근무 중"&&a.userId===user.id&&<button onClick={()=>clockOut(a.id)}>퇴근</button>}</article>)}{data.attendance.length===0&&<p className={styles.empty}>아직 출근 기록이 없습니다.</p>}</div></Panel></>}
      {view==="guide"&&<Guide/>}
    </section></div>
    {guide&&<div className={styles.backdrop}><section className={styles.modal}><button className={styles.close} onClick={()=>setGuide(false)}>×</button><small className={styles.eyebrow}>5-MINUTE EXPERIENCE</small><h2>점포가 늘어도 한눈에 관리합니다</h2><p>본사·점주·직원 역할을 바꾸며 운영 흐름을 체험해보세요.</p><div className={styles.guide}>{[["1","지도·점포 목록","전국 분포와 조치 대상을 확인"],["2","점포·계정 생성","본사는 점주, 점주는 직원을 관리"],["3","통합 수발주","요청부터 입고까지 상태 연결"],["4","GPS 출퇴근","등록 주소 반경 50m 판정"]].map(x=><article key={x[0]}><b>{x[0]}</b><span><strong>{x[1]}</strong><p>{x[2]}</p></span></article>)}</div><button className={styles.primary} onClick={()=>setGuide(false)}>체험 시작하기</button></section></div>}
    {modal==="store"&&<Modal title="신규 점포 생성" close={()=>setModal(null)}><form onSubmit={addStore}><div className={styles.formTwo}><label>점포명<input required value={storeDraft.name} onChange={e=>setStoreDraft({...storeDraft,name:e.target.value})}/></label><label>시·군·구<input required value={storeDraft.region} onChange={e=>setStoreDraft({...storeDraft,region:e.target.value})}/></label></div><label>도로명 주소<input required placeholder="서울 강동구 양재대로 1481" value={storeDraft.address} onChange={e=>setStoreDraft({...storeDraft,address:e.target.value})}/></label><label>점주 이름<input value={storeDraft.manager} onChange={e=>setStoreDraft({...storeDraft,manager:e.target.value})}/></label><div className={styles.formTwo}><label>위도<input required type="number" step="any" value={storeDraft.lat} onChange={e=>setStoreDraft({...storeDraft,lat:e.target.value})}/></label><label>경도<input required type="number" step="any" value={storeDraft.lng} onChange={e=>setStoreDraft({...storeDraft,lng:e.target.value})}/></label></div><small>실제 운영에서는 주소 검색만 하면 GPS 좌표가 자동 입력됩니다.</small><button className={styles.primary}>점포 생성</button></form></Modal>}
    {modal==="person"&&<Modal title="계정 생성" close={()=>setModal(null)}><form onSubmit={addPerson}><label>이름<input required value={personDraft.name} onChange={e=>setPersonDraft({...personDraft,name:e.target.value})}/></label><label>로그인 ID<input required value={personDraft.loginId} onChange={e=>setPersonDraft({...personDraft,loginId:e.target.value})}/></label>{role==="hq"&&<label>역할<select value={personDraft.role} onChange={e=>setPersonDraft({...personDraft,role:e.target.value as Role})}><option value="manager">점주·지점장</option><option value="staff">점포 직원</option><option value="hq">본사 관리자</option></select></label>}<label>배정 점포<select value={personDraft.storeId} onChange={e=>setPersonDraft({...personDraft,storeId:e.target.value})}>{(role==="hq"?data.stores:accessible).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button className={styles.primary}>임시 비밀번호로 생성</button></form></Modal>}
    {modal==="order"&&<Modal title="물품 요청" close={()=>setModal(null)}><form onSubmit={addOrder}><label>요청 점포<select value={storeId} onChange={e=>setStoreId(e.target.value)}>{accessible.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>품목<select value={orderDraft.item} onChange={e=>setOrderDraft({...orderDraft,item:e.target.value})}>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><div className={styles.formTwo}><label>수량<input required min="1" step="1" type="number" value={orderDraft.qty} onChange={e=>setOrderDraft({...orderDraft,qty:Number(e.target.value)})}/></label><label>필요일<input required type="date" value={orderDraft.needed} onChange={e=>setOrderDraft({...orderDraft,needed:e.target.value})}/></label></div><label>요청 사유<textarea required value={orderDraft.note} onChange={e=>setOrderDraft({...orderDraft,note:e.target.value})}/></label><button className={styles.primary}>본사에 요청</button></form></Modal>}
  </main>
}

function Map({stores,low,pick}:{stores:Store[];low:(s:Store)=>number;pick:(id:string)=>void}){return <div className={styles.map}><div className={styles.peninsula}/>{stores.map(s=>{const left=(s.lng-125.7)/4*78+10,top=(38.4-s.lat)/5.4*76+10,n=low(s);return <button key={s.id} title={`${s.name} · 부족 ${n}`} className={n>=3?styles.pinBad:n?styles.pinWarn:styles.pinGood} style={{left:`${left}%`,top:`${top}%`}} onClick={()=>pick(s.id)}><i/>{s.name}</button>})}<span>체험용 축약 지도</span></div>}
function StoreList({stores,low,pending,pick}:{stores:Store[];low:(s:Store)=>number;pending:(id:string)=>number;pick:(id:string)=>void}){return <div className={styles.storeTable}>{stores.map(s=><button key={s.id} onClick={()=>pick(s.id)}><span><b>{s.name}</b><small>{s.region} · {s.manager}</small></span><em>부족 <strong>{low(s)}</strong></em><em>발주 <strong>{pending(s.id)}</strong></em><i>보기 ›</i></button>)}</div>}
function Filters({query,setQuery,filter,setFilter}:{query:string;setQuery:(s:string)=>void;filter:string;setFilter:(s:string)=>void}){return <div className={styles.filters}><input placeholder="점포명·지역·점주 검색" value={query} onChange={e=>setQuery(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">전체 상태</option><option value="alert">조치 필요</option><option value="normal">정상</option></select></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className={styles.backdrop}><section className={styles.form}><button type="button" className={styles.close} onClick={close}>×</button><small className={styles.eyebrow}>INTERACTIVE DEMO</small><h2>{title}</h2>{children}</section></div>}
function Title({eyebrow,title,body,action,label}:{eyebrow:string;title:string;body:string;action?:()=>void;label?:string}){return <header className={styles.title}><div><small className={styles.eyebrow}>{eyebrow}</small><h1>{title}</h1><p>{body}</p></div>{action&&<button className={styles.primary} onClick={action}>{label}</button>}</header>}
function Metric({label,value,sub,warn}:{label:string;value:number;sub:string;warn?:boolean}){return <article className={warn?styles.warn:""}><span>{label}</span><strong>{value.toLocaleString()}</strong><small>{sub}</small></article>}
function Panel({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <section className={styles.panel}><header><h2>{title}</h2><p>{sub}</p></header>{children}</section>}
function Status({value}:{value:OrderStatus}){return <b className={`${styles.status} ${styles[`s${value.replace(" ","")}`]}`}>{value}</b>}
function Guide(){return <><Title eyebrow="WHY STORE HUB?" title="점포가 늘수록 더 강력해집니다" body="지역별 현황, 계정 권한, 수발주와 근태까지 하나로 연결합니다."/><div className={styles.features}>{[["전국 지도","점포 분포와 이상 상태를 빠르게 확인"],["계층형 권한","본사는 점주를, 점주는 직원을 관리"],["통합 재고","전체와 점포별 현재고를 동시에 집계"],["스마트 수발주","요청·승인·출고·입고 상태 연결"],["GPS 근태","등록 주소 50m 이내 출근만 인정"],["확장 구조","수십 개 점포도 검색·필터로 관리"]].map((x,i)=><article key={x[0]}><small>0{i+1}</small><h2>{x[0]}</h2><p>{x[1]}</p><b>본사와 점포가 같은 데이터를 봅니다.</b></article>)}</div></>}
